# Generated by Django 6.0.4 on 2026-04-21 07:59

from django.conf import settings
from django.db import migrations, models


def dedupe_applications(apps, schema_editor):
    Application = apps.get_model("applications", "Application")

    # Keep the oldest row (smallest id) for each (user, job), delete the rest.
    seen = set()
    duplicates = []
    for app in Application.objects.order_by("id").values_list("id", "user_id", "job_id"):
        app_id, user_id, job_id = app
        key = (user_id, job_id)
        if key in seen:
            duplicates.append(app_id)
        else:
            seen.add(key)

    if duplicates:
        Application.objects.filter(id__in=duplicates).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_application_status'),
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(dedupe_applications, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('user', 'job'), name='unique_application_per_user_job'),
        ),
    ]
